[platformio]
default_envs = APP_STLINK
include_dir = Inc
src_dir = Src

[env]
platform = ststm32
framework = stm32cube
board = genericSTM32F103C8
debug_tool = stlink
upload_protocol = stlink
build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

[env:APP_STLINK]
board_build.ldscript = ld/app.ld
board_upload.offset_address = 0x08001800
build_src_filter =
    -<*>
    +<main.c>
    +<board.c>
    +<imu_mpu6xxx.c>
    +<imu_preintegrator.c>
    +<imu_calibration.c>
    +<eskf_nav.c>
    +<vesc_packet.c>
    +<eeprom_flash.c>

[env:BOOTLOADER_STLINK]
board_build.ldscript = ld/bootloader.ld
board_upload.offset_address = 0x08000000
build_src_filter =
    -<*>
    +<bootloader.c>

[env:APP_USART]
board_build.ldscript = ld/app.ld
build_src_filter =
    -<*>
    +<main.c>
    +<board.c>
    +<imu_mpu6xxx.c>
    +<imu_preintegrator.c>
    +<imu_calibration.c>
    +<eskf_nav.c>
    +<vesc_packet.c>
    +<eeprom_flash.c>
upload_protocol = custom
upload_command = python3 tools/flash_uart.py $SOURCE --baud 921600
